metrics:
  video_integrity:
    enabled: true
    device: cuda
    batch_size: 1
  temporal_consistency:
    enabled: false
    model_path: pretrained_models/temporal/model.pt
    device: cuda
    batch_size: 1
  appearance_consistency:
    enabled: false
    model_path: pretrained_models/appearance/model.pt
    device: cuda
    batch_size: 1
  depth_consistency:
    enabled: false
    model_path: pretrained_models/depth/model.pt
    device: cuda
    batch_size: 1
  semantic_consistency:
    enabled: false
    repo_path: src/third_party/OpenSeeD
    device: cuda
    batch_size: 1
  instance_consistency:
    enabled: false
    model_path: pretrained_models/instance/model.pt
    device: cuda
    batch_size: 1
  view_consistency:
    enabled: false
    model_path: pretrained_models/view/model.pt
    device: cuda
    batch_size: 1
